import { Event, Attendee, Payout } from './types';

export const INITIAL_EVENTS: Event[] = [
  {
    id: 'ev-1',
    title: 'Underground Rituals: DJ Set',
    subtitle: 'An immersive descent into analog synthesis, visual echoes, and spatial acoustics.',
    description: 'A subterranean exploration of electronic music and industrial atmosphere. Join us at Factory No. 9 for a curated lineup of underground selectors, high-fidelity sound systems, and responsive light art. Let the frequency guide your motion through the architectural remnants of LA\'s industrial core.',
    date: 'July 18, 2026',
    time: '22:00 - 04:00',
    location: 'Factory No. 9, Los Angeles',
    image: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&q=80&w=800',
    status: 'active',
    tags: ['Electronic', 'Warehouse', 'Industrial'],
    tiers: [
      {
        id: 'tier-early',
        name: 'Early Bird Access',
        price: 35,
        capacity: 100,
        soldCount: 100,
        description: 'Includes entry before 23:00. Sold out.',
        status: 'sold_out',
      },
      {
        id: 'tier-phase1',
        name: 'Phase 1: Release',
        price: 55,
        capacity: 250,
        soldCount: 142,
        description: 'General admission entry. Standard access tier.',
        status: 'available',
      },
      {
        id: 'tier-phase2',
        name: 'Phase 2: Final',
        price: 75,
        capacity: 150,
        soldCount: 12,
        description: 'Late access tier. Limited quantities remain.',
        status: 'available',
      },
      {
        id: 'tier-vip',
        name: 'VIP Delegate Pass',
        price: 150,
        capacity: 50,
        soldCount: 30,
        description: 'Priority entry, dedicated sound area, and complimentary catalog.',
        status: 'available',
      }
    ]
  },
  {
    id: 'ev-2',
    title: 'Ambient Solstice: Sound Bath',
    subtitle: 'A collective meditation on drone acoustics and restorative analog frequencies.',
    description: 'Align your system with the natural shift of light. The Sanctuary plays host to a 3-hour ambient landscape utilizing rare vintage synthesizers, crystal resonators, and field recordings. Lay back, breathe deeply, and dissolve into the harmonic warmth of the solstice.',
    date: 'June 21, 2026',
    time: '18:00 - 21:00',
    location: 'The Sanctuary, Malibu',
    image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=800',
    status: 'completed',
    tags: ['Wellness', 'Ambient', 'Live Sound'],
    tiers: [
      {
        id: 'tier-sol-gen',
        name: 'Mats & Blanket Tier',
        price: 75,
        capacity: 80,
        soldCount: 80,
        description: 'Premium floor setup with custom organic cotton bedding.',
        status: 'sold_out',
      }
    ]
  },
  {
    id: 'ev-3',
    title: 'Modular Synthesis Workshop',
    subtitle: 'Hands-on exploration of CV routing, wavefolding, and generative patches.',
    description: 'An intimate masterclass in subtractive and additive Eurorack patching. Led by resident technicians at Audio Labs. Bring your own skiff or use our provided test-benches. Includes lunch and custom design notebooks.',
    date: 'August 04, 2026',
    time: '10:00 - 17:00',
    location: 'Audio Labs, Brooklyn',
    image: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80&w=800',
    status: 'active',
    tags: ['Workshop', 'Hardware', 'Generative'],
    tiers: [
      {
        id: 'tier-mod-gen',
        name: 'General Admission',
        price: 110,
        capacity: 30,
        soldCount: 22,
        description: 'Full workspace and kit access included.',
        status: 'available',
      }
    ]
  },
  {
    id: 'ev-4',
    title: 'Neo-Classical Night',
    subtitle: 'Unamplified acoustic pianos coupled with dark sub-bass textures.',
    description: 'An elegant performance merging minimalist classical strings and microtonal modular sub-basses. Performed inside the reverberant stone chambers of the Cathedral Room. An unforgettable auditory dialogue between ancient stone and custom electronics.',
    date: 'August 28, 2026',
    time: '20:30 - 23:00',
    location: 'Cathedral Room, Seattle',
    image: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?auto=format&fit=crop&q=80&w=800',
    status: 'active',
    tags: ['Classical', 'Acoustic', 'Atmospheric'],
    tiers: [
      {
        id: 'tier-neo-gen',
        name: 'Pew Seating',
        price: 60,
        capacity: 120,
        soldCount: 85,
        description: 'General unreserved seating in the historical pews.',
        status: 'available',
      },
      {
        id: 'tier-neo-balcony',
        name: 'Gallery Balcony Access',
        price: 90,
        capacity: 40,
        soldCount: 40,
        description: 'Elevated acoustic perspective and dedicated entrance.',
        status: 'sold_out',
      }
    ]
  }
];

export const INITIAL_ATTENDEES: Attendee[] = [
  {
    id: 'at-1',
    name: 'Sarah Jenkins',
    email: 'sarah.j@ambientspace.co',
    ticketClass: 'Phase 1: Release',
    ticketPrice: 55,
    purchaseDate: 'July 02, 2026',
    status: 'registered',
    eventId: 'ev-1',
    eventTitle: 'Underground Rituals: DJ Set',
  },
  {
    id: 'at-2',
    name: 'Liam Carter',
    email: 'l.carter@modulartracks.io',
    ticketClass: 'VIP Delegate Pass',
    ticketPrice: 150,
    purchaseDate: 'June 28, 2026',
    status: 'checked_in',
    eventId: 'ev-1',
    eventTitle: 'Underground Rituals: DJ Set',
  },
  {
    id: 'at-3',
    name: 'Chloe Patel',
    email: 'chloe.patel@soundwave.org',
    ticketClass: 'Early Bird Access',
    ticketPrice: 35,
    purchaseDate: 'June 15, 2026',
    status: 'checked_in',
    eventId: 'ev-1',
    eventTitle: 'Underground Rituals: DJ Set',
  },
  {
    id: 'at-4',
    name: 'Marcus Vance',
    email: 'mvance@frequency.net',
    ticketClass: 'Phase 1: Release',
    ticketPrice: 55,
    purchaseDate: 'July 04, 2026',
    status: 'registered',
    eventId: 'ev-1',
    eventTitle: 'Underground Rituals: DJ Set',
  },
  {
    id: 'at-5',
    name: 'Aisha Rahman',
    email: 'aisha@soundresonance.com',
    ticketClass: 'VIP Delegate Pass',
    ticketPrice: 150,
    purchaseDate: 'July 01, 2026',
    status: 'registered',
    eventId: 'ev-1',
    eventTitle: 'Underground Rituals: DJ Set',
  },
  {
    id: 'at-6',
    name: 'Daniel Kim',
    email: 'dan.kim@seattlepiano.net',
    ticketClass: 'Early Bird Access',
    ticketPrice: 35,
    purchaseDate: 'June 14, 2026',
    status: 'refunded',
    eventId: 'ev-1',
    eventTitle: 'Underground Rituals: DJ Set',
  },
  {
    id: 'at-7',
    name: 'Sophia Martinez',
    email: 'sophia.m@rituals.la',
    ticketClass: 'Phase 2: Final',
    ticketPrice: 75,
    purchaseDate: 'July 05, 2026',
    status: 'registered',
    eventId: 'ev-1',
    eventTitle: 'Underground Rituals: DJ Set',
  },
  {
    id: 'at-8',
    name: 'James Reynolds',
    email: 'james@reynoldsdesign.co',
    ticketClass: 'Phase 1: Release',
    ticketPrice: 55,
    purchaseDate: 'July 06, 2026',
    status: 'registered',
    eventId: 'ev-1',
    eventTitle: 'Underground Rituals: DJ Set',
  },
  {
    id: 'at-9',
    name: 'Elena Rostova',
    email: 'e.rostova@synthesist.de',
    ticketClass: 'VIP Delegate Pass',
    ticketPrice: 150,
    purchaseDate: 'July 03, 2026',
    status: 'checked_in',
    eventId: 'ev-1',
    eventTitle: 'Underground Rituals: DJ Set',
  },
  {
    id: 'at-10',
    name: 'Tyler Durden',
    email: 'tyler@soapfreq.com',
    ticketClass: 'Phase 2: Final',
    ticketPrice: 75,
    purchaseDate: 'July 06, 2026',
    status: 'registered',
    eventId: 'ev-1',
    eventTitle: 'Underground Rituals: DJ Set',
  }
];

export const INITIAL_PAYOUTS: Payout[] = [
  {
    id: 'p-1',
    date: 'June 30, 2026',
    amount: 14250.00,
    bankAccount: 'WELLS FARGO (****4829)',
    status: 'completed',
  },
  {
    id: 'p-2',
    date: 'June 15, 2026',
    amount: 8900.00,
    bankAccount: 'WELLS FARGO (****4829)',
    status: 'completed',
  },
  {
    id: 'p-3',
    date: 'May 31, 2026',
    amount: 12400.00,
    bankAccount: 'WELLS FARGO (****4829)',
    status: 'completed',
  },
  {
    id: 'p-4',
    date: 'May 15, 2026',
    amount: 7300.00,
    bankAccount: 'WELLS FARGO (****4829)',
    status: 'completed',
  }
];
